# UTS-2 My Songs for You

Title: Spiral

Vocals, Lyrics, Composing: LONGMAN

{{< video https://www.youtube.com/watch?v=fE9trKOuT3Q>}}

Saya percaya bahwa penggunaan Generative AI tidak etis jika dipakai untuk membuat "karya," karena sejatinya dataset training Generative AI berasal dari artist-artist lain tanpa consent mereka. Hal ini bisa disimpulkan sebagai plagiarisme, meskipun secara teknis, AI "membuat lagu baru," namun hal yang "diciptakan" oleh AI adalah hasil karya orang lain. Sehingga, saya lebih memilih untuk menggunakan karya orang lain dengan credit, tentunya, tanpa mengklaim saya memiliki andil dalam pembuatannya.

Lyrics (Translation):
I tore up the map I drew.

My world is still the same as that day.

I’m putting the blame on someone else again.

I hate myself for this…


I pretend to keep waiting for something like this.

Can I start over from here?


I felt like I could go anywhere.

Where am I from that time now?

I’m sure I’ve grown up,

But actually it’s not.


I had a tomorrow that I could change,

If I had a little more courage.

But I didn’t notice even it.

I wonder how many times there were such moments?


I have untied the threads we have tied.

My world is still the same as that day.

I just do the same again.

I hate myself for this…


By accepting my selfish dream and personally destroying it,

What do I want to do?

Will you ever break through this darkness to me?

Oh, my life.


Our justice is surely

A hindrance to someone else.

I’m sure there’s nothing to be done about it,

But actually it’s not.


I have a tomorrow that I can protect,

If I get a little stronger.

If even on the night, when everything changed,

I could laugh, saying: “From here again…”


Twisted emotions, don’t show up.

I’m sure I could change, it’s time to say goodbye to you.

I wish for you, for someone

To become a star that will not disappear

In an endless night, but I could not.

We are still the same as we were.


I had a tomorrow that I could change,

If I had a little more courage.

But I didn’t notice even it.

There have already been many such days.


Nothing is endless…

Before it’s over,

I tried to take a step forward,

Accepting this fact and praying.

Lagu ini menceritakan tentang seorang shut-in yang takut untuk melangkah lebih jauh. Takut untuk mulai beraksi, takut untuk berubah, terlalu nyaman dalam kehangatan kamarnya.
If I could go into a time machine, I would give this song to my past self, who is exactly what this song describes. Saya adalah seorang pengecut yang tak ingin keluar dari zona nyaman saya. If only I've known this song a long time ago, I would've done so much. I could've been the person I dreamt of as a kid.

Lagu ini juga saya tujukan kepada pembaca yang merasa takut untuk melangkah. Keluarlah dari kenyamanan dirimu saat ini. Break out of the bubble, and you won't regret it. You would probably be surprised by all the things you could've done all this time.
